export const LOAD_COURSES_START = "LOAD_COURSES_START";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_COURSES_ERROR = "LOAD_COURSES_ERROR";

export const CREATE_COURSE_START = "CREATE_COURSE_START";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_ERROR = "CREATE_COURSE_ERROR";

export const DELETE_COURSE_START = "DELETE_COURSE_START";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_ERROR = "DELETE_COURSE_ERROR";

export const UPDATE_COURSE_START = "UPDATE_COURSE_START";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_ERROR = "UPDATE_COURSE_ERROR";